accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    # Registration
    path('vendor/signup/', views.vendor_signup, name='vendor_signup'),
    path('customer/signup/', views.customer_signup, name='customer_signup'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # Customer account
    path('customer/', views.customer_account, name='customer'),
    path('customer/orders/', views.customer_orders, name='orders'),
    path('customer/addresses/', views.customer_addresses, name='addresses'),
    path('customer/wishlists/', views.customer_wishlist, name='wishlist'),

    # Vendor account
    path('vendors/', views.vendors, name='vendors'),
    path('vendor/', views.vendor_account, name='vendor'),
    path('vendor/orders/', views.vendor_orders, name='vendor_orders'),
    path('vendor/products/', views.vendor_products, name='vendor_products'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),

    path('deactivate/', views.deactivate, name='deactivate'),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_ecommerce/urls.py
"""django_ecommerce URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path("cart/", include("carts.urls", namespace="carts")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("products/", include("products.urls", namespace="products")),
    # password reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("", home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.index_title = "Lunch Express"
admin.site.site_header = "Lunch Express Admin"
admin.site.site_title = "Control Panel"

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('track-order/<int:id>/', views.track_order, name='track_order'),
    path('status/shipped/<int:id>/',
         views.order_status_shipped, name='order_status_shipped'),
    path('status/processing/<int:id>/',
         views.order_status_processing, name='order_status_processing'),
    path('status/completed/<int:id>/',
         views.order_status_completed, name='order_status_completed'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('c/<slug:category_slug>/', views.product_list, name='category'),
    path('vote/', views.vote_review, name="vote_review"),
    path('search/', views.product_search, name='search'),
    path('new/', views.product_create, name='create'),
    path('<int:id>/update/', views.product_update, name='update'),
    path('<int:id>/delete/', views.product_delete, name='delete'),
    path('<slug:slug>/', views.product_detail, name='detail'),
]

orders/models.py
from datetime import datetime, timedelta
from django.db import models

from accounts.models import User, Vendor
from products.models import Product


class Order(models.Model):
    CREATED = 'Created'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    COMPLETED = 'Completed'
    # CANCELLED = 'Cancelled'
    # RETURNED = 'Returned'
    ORDER_STATUS = [
        (CREATED, 'Created'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (COMPLETED, 'Completed'),
        # (CANCELLED, 'Cancelled'),
        # (RETURNED, 'Returned'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='orders',
        blank=True, null=True) # models.SET_NULL
    # full_name?
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    # address1 / address2?
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=5)
    phone_number = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField(
        choices=ORDER_STATUS, max_length=10, default=CREATED)
    note = models.TextField(blank=True)
    delivery_date = models.DateTimeField(default=datetime.now()+timedelta(days=4))
    # transaction_id = models.CharField(max_length=200, blank=True, null=True)
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2,
        blank=True, null=True)
    paystack_id = models.CharField(max_length=150, blank=True)
    vendors = models.ManyToManyField(Vendor, related_name='orders')

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='orderitems',
        blank=True, null=True)
    vendor = models.ForeignKey(
        Vendor, related_name='items',
        on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # vendor_paid = models.BooleanField(default=False)
    # status?

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
    <div class="position-fixed top-0 start-50 translate-middle-x p-3" style="z-index: 11;">
      <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" data-bs-delay="10000" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">{{ message }}</div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
      </div>
    </div>
    {% endfor %}
{% endif %}

templates/partials/_customer_nav.html
<aside class="col-lg-3">
<nav class="nav flex-lg-column nav-pills mb-4">
    <a class="nav-link {% url 'accounts:customer' as customer_url %}{% if request.get_full_path == customer_url %}active{% endif %}" href="{% url 'accounts:customer' %}">My Account</a>
    <a class="nav-link {% url 'accounts:orders' as orders_url %}{% if request.get_full_path == orders_url %}active{% endif %}" href="{% url 'accounts:orders' %}">Orders history</a>
    <!-- <a class="nav-link {% url 'accounts:wishlist' as wishlist_url %}{% if request.get_full_path == wishlist_url %}active{% endif %}" href="{% url 'accounts:wishlist' %}">My wishlist</a>
    <a class="nav-link {% url 'accounts:addresses' as addresses_url %}{% if request.get_full_path == addresses_url %}active{% endif %}" href="{% url 'accounts:addresses' %}">Addresses</a> -->
    <a class="nav-link {% url 'accounts:password_change' as password_change_url %}{% if request.get_full_path == password_change_url %}active{% endif %}" href="{% url 'accounts:password_change' %}">Change Password</a>
    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
</nav>
</aside>

templates/partials/_food_card.html
<div class="col-lg-4 col-md-6">
    <article class="card card-product-grid"> 
        <a href="{{ product.get_absolute_url }}"> 
            <img src="{{ product.image.url }}" height="200" class="card-img-top" alt="{{ product.name }}"> 
        </a>
        <div class="card-body pt-0">
            <div class="pt-3 pe-5">
                <h6 class="card-title mb-0"> 
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> 
                </h6>
                <p class="mb-1 text-muted">{{ product.description|truncatechars:100 }}</p> 
                <span class="badge bg-warning"> &#8358;{{ product.price }} </span> 
                <span class="text-success small ms-2"> <i class="fa fa-truck"></i> {{ product.delivery_time }}</span> 
            </div>
        </div>
    </article>
</div>

templates/partials/_footer.html
<footer class="section-footer bg-dark footer-dark mt-auto">
    <div class="container">
        <section class="footer-bottom d-flex justify-content-lg-between border-top">
            <p class="text-muted mb-0"> &copy; {% now "Y" %} Lunch Express. All rights reserved. </p>
            <nav>
                <span>
                    <i class="fas fa-heart text-danger"></i>
                    Final Year Project
                </span>
            </nav>
        </section>
    </div>
    <!-- container end.// -->
</footer>

templates/partials/_form_errors.html
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    <p {% if forloop.last %}class="mb-0" {% endif %}>{{ error }}</p>
    {% endfor %}
</div>
{% endif %}

{% for hidden_field in form.hidden_fields %}
    {% if hidden_field.errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in hidden_field.errors %}
                <p {% if forloop.last %}class="mb-0" {% endif %}>(Hidden field {{ hidden_field.name }}) {{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
{% endfor %}

templates/partials/_navbar.html
<header>
    <section class="py-3 border-bottom">
        <div class="container">
            <div class="row g-3 align-items-center">
                <div class="col-lg-2 col-sm-3 col-4">
                    <h3 class="m-0 p-0"><a class="link-info text-decoration-none" href="{% url 'home' %}">Lunch
                            Express</a></h3>
                </div>
                <div class="col-lg-5 col-sm-5 col-8">
                    <form action="{% url 'products:search' %}" method="get" class="me-3">
                        <div class="input-group">
                            <input type="search" class="form-control" placeholder="Search" name="keyword"
                                value="{{ request.GET.keyword }}">
                            <button class="input-group-text btn btn-light" type="submit"> <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>

                <div class="1ms-auto col-lg-5 col-sm-4 col-12">
                    <div class="float-md-end">
                        <div class="d-inline-block position-relative align-middle me-2">
                            {% if not request.user.is_vendor %}
                            {% with total_items=cart|length %}
                            <a href="{% url 'carts:cart_detail' %}" class="btn btn-light position-relative">
                                <i class="fa fa-shopping-cart"></i>
                                <span class="ms-1">Cart </span>
                                <b
                                    class="fs-6 lh-1 py-1 rounded-pill px-2 d-inline-block text-center text-white bg-danger position-absolute top-0 start-100 translate-middle">
                                    {% if total_items > 0 %}{{ total_items }}{% else %}0{% endif %} </b>
                            </a>
                            {% endwith %}
                            {% else %}
                            <a href="{% url 'products:create' %}" class="btn btn-light">
                                <i class="fa fa-upload"></i> Upload a Meal
                            </a>
                            {% endif %}
                        </div>

                        {% if request.user.is_authenticated %}
                        <div class="d-inline-block position-relative align-middle me-2">
                            {% if request.user.is_customer %}
                            <a href="{% url 'accounts:customer' %}" class="btn btn-light">
                                <i class="fa fa-user"></i> My Account
                            </a>
                            {% elif request.user.is_vendor %}
                            <a href="{% url 'accounts:vendor' %}" class="btn btn-light">
                                <i class="fa fa-bars"></i> Dashboard
                            </a>
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <nav class="navbar navbar-light navbar-expand-md border-bottom">
        <div class="container">
            <button class="navbar-toggler border" type="button" data-bs-toggle="collapse" data-bs-target="#navbarmenu"
                aria-expanded="false" aria-label="Toggle navigation" aria-controls="navbarmenu">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarmenu">
                <ul class="navbar-nav">
                    <li class="nav-item"> <a
                            class="nav-link ps-0 {% url 'home' as home_url %}{% if request.get_full_path == home_url %}active{% endif %}"
                            href="{% url 'home' %}"> Home </a> </li>
                    <li class="nav-item"> <a
                            class="nav-link {% url 'products:list' as product_list_url %}{% if request.get_full_path == product_list_url %}active{% endif %}"
                            href="{% url 'products:list' %}">Meals</a> </li>
                    <li class="nav-item"> <a
                            class="nav-link {% url 'accounts:vendors' as vendors_url %}{% if request.get_full_path == vendors_url %}active{% endif %}"
                            href="{% url 'accounts:vendors' %}">Vendors</a> </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:customer_signup' %}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/partials/_order_card.html
<article class="card mb-3">
    <div class="card-body p-4">
        <header class="d-lg-flex">
            <div class="flex-grow-1">
                <h6 class="mb-0">
                    Order ID: {{ order.id }} &bull;
                    <span class="text-success">{{ order.get_status_display }}</span>
                </h6>
                <span class="text-muted">Date: {{ order.created|date:"j F Y" }}</span>
            </div>
            {% if not request.user.is_vendor %}
            <div>
                <a href="{% url 'orders:track_order' order.id %}" class="btn btn-sm btn-primary">Track order</a>
            </div>
            {% else %}
            <div class="float-lg-end d-flex mb-3">
                <div class="dropdown btn btn-light btn-sm float-end"> 
                    <a href="#" data-bs-toggle="dropdown" aria-expanded="false" id="moreOptions"><i class="fa fa-ellipsis-v"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="moreOptions">
                        {% if order.status == 'Created' %}
                        <li><a class="dropdown-item" href="{% url 'orders:order_status_processing' order.id %}">Order Processing</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_shipped' order.id %}">Order Shipped</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_completed' order.id %}">Order Completed</a></li>

                        {% elif order.status == 'Processing' %}
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_processing' order.id %}">Order Processing</a></li>
                        <li><a class="dropdown-item" href="{% url 'orders:order_status_shipped' order.id %}">Order Shipped</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_completed' order.id %}">Order Completed</a></li>

                        {% elif order.status == 'Shipped' %}
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_processing' order.id %}">Order Processing</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_shipped' order.id %}">Order Shipped</a></li>
                        <li><a class="dropdown-item" href="{% url 'orders:order_status_completed' order.id %}">Order Completed</a></li>

                        {% elif order.status == 'Completed' %}
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_processing' order.id %}">Order Processing</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_shipped' order.id %}">Order Shipped</a></li>
                        <li><a class="dropdown-item disabled" href="{% url 'orders:order_status_completed' order.id %}">Order Completed</a></li>

                        {% endif %}

                    </ul>
                </div>
            </div>
            {% endif %}
        </header>
        <hr>
        <div class="row">
            <div class="col-lg-4">
                <p class="mb-0 text-muted">Contact</p>
                <p class="m-0">
                    {{ order.first_name }} {{ order.last_name }} <br> Email: {{ order.user.email }} </p>
            </div>
            <div class="col-lg-4 border-start">
                <p class="mb-0 text-muted">Shipping address</p>
                <p class="m-0">{{ order.address }} </p>
            </div>
            <div class="col-lg-4 border-start">
                <p class="mb-0 text-muted">Payment</p>
                <p class="m-0">
                    <span class="text-success"> Total paid: &#8358;{{ order.get_total_cost }}
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <ul class="steps-wrap mx-auto">
                <li class="step {% if order.status == 'Created' or order.status == 'Processing' or order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                    <span class="icon">1</span> 
                    <span class="text">Order created</span> 
                </li>
                <li class="step {% if order.status == 'Processing' or order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                    <span class="icon">2</span> 
                    <span class="text">Order processed</span> 
                </li>
                <li class="step {% if order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                    <span class="icon">3</span> 
                    <span class="text">Order shipped</span> 
                </li>
                <li class="step {% if order.status == 'Completed' %}active{% endif %}"> 
                    <span class="icon">4</span> 
                    <span class="text">Order completed</span> 
                </li>
            </ul>
        </div>
        <!-- <ul class="row">
            {% for item in order.items.all %}
            <li class="col-lg-4">
                <figure class="itemside mb-3">
                    <div class="aside">
                        <img width="72" height="72" src="{{ item.product.image.url }}" class="img-sm rounded border">
                    </div>
                    <figcaption class="info">
                        <p class="title">{{ item.product.name }}</p>
                        <strong> {{ item.quantity }}x = &#8358;{{ item.price }} </strong>
                    </figcaption>
                </figure>
            </li>
            {% endfor %}
        </ul> -->
    </div>
</article>

templates/partials/_pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Pagination" class="mt-3">
    <ul class="pagination justify-content-center">

        {% if page_obj.number > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">First</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">First</span>
        </li>
        {% endif %}

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active">
            <span class="page-link">
                {{ page_num }}
            </span>
        </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        {% if page_obj.number != page_obj.paginator.num_pages %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Last</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Last</span>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}

templates/partials/_product_grid.html
<div class="col-lg-3 col-sm-6 col-12">
    <figure class="card card-product-grid">
        <div class="img-wrap">
            <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"></a>
        </div>
        <figcaption class="info-wrap"> 
            <!-- <small class="text-muted"><a href="#" class="title">{{ product.vendor.vendor.company_name }}</a></small> -->
            <p class="title"><a href="{{ product.get_absolute_url }}" class="text-decoration-none">{{ product.name }}</a></p>
            <div class="rating-wrap">
                <div class="rating-star">
                    <span>
                        <i class="fa fa-star{% if product.average_review < 0.5 %}-o{% elif product.average_review >= 0.5 and product.average_review < 1%}-half-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if product.average_review < 1.5 %}-o{% elif product.average_review >= 1.5 and product.average_review < 2%}-half-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if product.average_review < 2.5 %}-o{% elif product.average_review >= 2.5 and product.average_review < 3%}-half-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if product.average_review < 3.5 %}-o{% elif product.average_review >= 3.5 and product.average_review < 4%}-half-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if product.average_review < 4.5 %}-o{% elif product.average_review >= 4.5 and product.average_review < 5%}-half-o{% endif %}" aria-hidden="true"></i>
                    </span> 
                    <span class="label-rating text-warning">{{ product.average_review }}</span> 
                </div>
            </div>
        </figcaption>
        <div class="bottom-wrap"> 
            <a href="javascript:void(0)" class="btn btn-primary float-end add-cart" data-product="{{ product.id }}" data-action="add"><i class="fa fa-shopping-cart"></i></a>
            <div class="price-wrap lh-sm"> 
                <strong class="price">&#8358;{{ product.price }}</strong>
                <!-- <small class="text-danger">{% if product.units <= 0 %}Out of Stock{% endif %}</small>  -->
            </div>
        </div>
    </figure>
</div>

templates/partials/_products_list.html
    <article class="card 1card-product-grid"> 
        <a href="{{ product.get_absolute_url }}"> 
            <img src="{{ product.image.url }}" height="200" class="card-img-top" alt="{{ product.name }}"> 
        </a>
        <div class="card-body pt-0">
            <div class="pt-3 pe-5">
                <h6 class="card-title mb-0"> 
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> 
                </h6>
                <p class="mb-1 text-muted">{{ product.description|truncatechars:100 }}</p> 
                <span class="badge bg-warning"> &#8358;{{ product.price|floatformat:2 }} </span> 
                <span class="text-success small ms-2"> <i class="fa fa-truck"></i> {{ product.delivery_time }}</span> 
            </div>
        </div>
    </article>

templates/partials/_vendor_card.html
<div class="card mb-4">
    <div class="card-body">
        <div class="itemside mb-4">
            <div class="aside"> 
                <img src="{{ vendor.image.url }}" width="60" height="60" class="img-sm img-thumbnail"> 
            </div>
            <div class="info"> 
                <span class="h6 title">{{ vendor.company_name }}</span>
                <small class="text-muted">Selling {{ vendor.user.products.count }} product{{ vendor.user.products.count|pluralize }}</small>
                <p><i class="fa fa-map-marker"></i> {{ vendor.address }}, {{ vendor.state }}</p>
            </div>
        </div>
        <p>{{ vendor.about|truncatechars:280 }}</p>
        <a href="{% url 'accounts:vendor_profile' vendor.user.username %}" class="btn w-100 btn-outline-primary">Visit store</a>
    </div>
</div>

<!-- <div 1class="col-lg-4">
    <div class="card">
        <article class="p-4 p-xl-5 text-center"> <img src="{{ vendor.image.url }}" class="img-avatar img-md">
            <h6 class="card-title mt-3">{{ vendor.company_name }}</h6>
            <p> {{ vendor.vendor.about|truncatechars:280 }}</p> 
           <a href="{% url 'accounts:vendor_profile' vendor.user.username %}" class="btn btn-success"> Visit Vendor </a> 
        </article>
    </div>
</div>-->

templates/partials/_vendor_nav.html
<aside class="col-lg-3">
<nav class="nav flex-lg-column nav-pills mb-4">
    <a class="nav-link {% url 'accounts:vendor' as vendor_url %}{% if request.get_full_path == vendor_url %}active{% endif %}" href="{% url 'accounts:vendor' %}">Manage Account</a>
    <a class="nav-link {% url 'accounts:vendor_products' as vendor_products_url %}{% if request.get_full_path == vendor_products_url %}active{% endif %}" href="{% url 'accounts:vendor_products' %}">Manage Products</a>
    <a class="nav-link {% url 'accounts:vendor_orders' as vendor_orders_url %}{% if request.get_full_path == vendor_orders_url %}active{% endif %}" href="{% url 'accounts:vendor_orders' %}">Manage Orders</a>
    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
</nav>
</aside>