accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    # Registration
    path('vendor/signup/', views.vendor_signup, name='vendor_signup'),
    path('customer/signup/', views.customer_signup, name='customer_signup'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # Customer account
    path('customer/', views.customer_account, name='customer'),
    path('customer/orders/', views.customer_orders, name='orders'),
    path('customer/addresses/', views.customer_addresses, name='addresses'),
    path('customer/wishlists/', views.customer_wishlist, name='wishlist'),

    # Vendor account
    path('vendors/', views.vendors, name='vendors'),
    path('vendor/', views.vendor_account, name='vendor'),
    path('vendor/orders/', views.vendor_orders, name='vendor_orders'),
    path('vendor/products/', views.vendor_products, name='vendor_products'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),

    path('deactivate/', views.deactivate, name='deactivate'),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_ecommerce/urls.py
"""django_ecommerce URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path("cart/", include("carts.urls", namespace="carts")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("products/", include("products.urls", namespace="products")),
    # password reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("", home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.index_title = "Lunch Express"
admin.site.site_header = "Lunch Express Admin"
admin.site.site_title = "Control Panel"

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('track-order/<int:id>/', views.track_order, name='track_order'),
    path('status/shipped/<int:id>/',
         views.order_status_shipped, name='order_status_shipped'),
    path('status/processing/<int:id>/',
         views.order_status_processing, name='order_status_processing'),
    path('status/completed/<int:id>/',
         views.order_status_completed, name='order_status_completed'),
]

accounts/models.py
# from django.core.validators import MinLengthValidator, MaxLengthValidator
# from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_vendor = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)


class Vendor(models.Model):
    """ Vendor model for storing vendor information. """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='vendor')
    company_name = models.CharField(max_length=50)
    address = models.CharField(max_length=600)
    about = models.TextField()
    image = models.ImageField(upload_to='vendor/images')
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return self.company_name


class Customer(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='customer')
    phone_number = models.CharField(
        max_length=20, blank=True, null=True)
    image = models.ImageField(
        upload_to='customer/images', blank=True, null=True)
    address = models.CharField(
        max_length=250, blank=True, null=True)

    @property
    def email(self):
        return f"{self.user.email}"

    def __str__(self):
        return f"{self.user.username} profile"


class LecturerPreference(models.Model):
    lecturer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    preferred_calories = models.IntegerField(blank=True, null=True)
    preferred_protein = models.IntegerField(blank=True, null=True)
    preferred_carbohydrates = models.IntegerField(blank=True, null=True)
    preferred_fats = models.IntegerField(blank=True, null=True)
    preferred_vitamins = models.IntegerField(blank=True, null=True)
    preferred_minerals = models.IntegerField(blank=True, null=True)
    preferred_fiber = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Food preference for #{self.lecturer.user.username}"

orders/models.py
from datetime import datetime, timedelta
from django.db import models

from accounts.models import User, Vendor
from products.models import Product


class Order(models.Model):
    CREATED = 'Created'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    COMPLETED = 'Completed'
    # CANCELLED = 'Cancelled'
    # RETURNED = 'Returned'
    ORDER_STATUS = [
        (CREATED, 'Created'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (COMPLETED, 'Completed'),
        # (CANCELLED, 'Cancelled'),
        # (RETURNED, 'Returned'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='orders',
        blank=True, null=True) # models.SET_NULL
    # full_name?
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    # address1 / address2?
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=5)
    phone_number = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField(
        choices=ORDER_STATUS, max_length=10, default=CREATED)
    note = models.TextField(blank=True)
    delivery_date = models.DateTimeField(default=datetime.now()+timedelta(days=4))
    # transaction_id = models.CharField(max_length=200, blank=True, null=True)
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2,
        blank=True, null=True)
    paystack_id = models.CharField(max_length=150, blank=True)
    vendors = models.ManyToManyField(Vendor, related_name='orders')

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='orderitems',
        blank=True, null=True)
    vendor = models.ForeignKey(
        Vendor, related_name='items',
        on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # vendor_paid = models.BooleanField(default=False)
    # status?

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['address'].widget.attrs.update(
            {'class': 'form-control'})

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from django_ecommerce.utils import mk_paginator
from products.models import Product
from orders.models import Order

from .decorators import redirect_authenticated_user
from .models import User, Vendor
from .forms import (
    CustomerSignUpForm, VendorSignUpForm, UserForm,
    CustomerForm, VendorForm)


@redirect_authenticated_user
def vendor_signup(request):
    if request.method == "POST":
        form = VendorSignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request, "Your registration was successful")
            return redirect("accounts:vendor")
        else:
            messages.warning(
                request, "An error occured. Please check below.")
    else:
        form = VendorSignUpForm()

    template_name = "vendor/signup.html"
    context = {
        "form": form,
        "user_type": "a vendor",
    }

    return render(request, template_name, context)


@redirect_authenticated_user
def customer_signup(request):
    if request.method == "POST":
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request, "Your account was successfully created.")
            # Send welcome email to customer
            return redirect("home")
        else:
            messages.warning(
                request, "An error occured. Please check below.")
    else:
        form = CustomerSignUpForm()

    template_name = "registration/signup.html"
    context = {
        "form": form,
        "user_type": "a customer",
    }

    return render(request, template_name, context)


@login_required
def vendor_account(request):
    if request.user.is_customer:
        return redirect("accounts:customer")
    if request.method == 'POST':
        form = VendorForm(
            request.POST, request.FILES,
            instance=request.user.vendor)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account was successully updated.')
            return redirect('accounts:vendor')
        else:
            messages.warning(
                request, 'There was an error while updating your account.')
    else:
        form = VendorForm(instance=request.user.vendor)

    template = 'vendor/account.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def customer_account(request):
    if request.user.is_vendor:
        return redirect("accounts:customer")
    if request.method == 'POST':
        user_form = UserForm(
            request.POST, instance=request.user)
        customer_form = CustomerForm(
            request.POST, request.FILES, instance=request.user.customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
            messages.success(request, 'Your account was successully updated.')
            return redirect('accounts:customer')
        else:
            messages.warning(
                request, 'There was an error while updating your account.')
    else:
        user_form = UserForm(instance=request.user)
        customer_form = CustomerForm(instance=request.user.customer)

    template = 'customer/account.html'
    context = {
        'user_form': user_form,
        'customer_form': customer_form,
    }

    return render(request, template, context)


@login_required
def customer_orders(request):
    orders = Order.objects.filter(
        user=request.user)

    template = 'customer/orders.html'
    context = {
        'orders': orders,
        'orders_count': orders.count()

    }

    return render(request, template, context)


@login_required
def customer_addresses(request):

    template = 'customer/addresses.html'
    context = {
    }

    return render(request, template, context)


@login_required
def customer_wishlist(request):

    template = 'customer/wishlist.html'
    context = {
    }

    return render(request, template, context)


@login_required
def deactivate(request):
    user = request.user
    # disable the user's password
    user.set_unusable_password()
    # deactivate the user's account
    user.is_active = False
    user.save()
    logout(request)
    messages.success(
        request, "Your account has been successfully deactivated.")
    return redirect('home')


def vendor_profile(request, username):
    user = get_object_or_404(
        User, username=username)
    products = Product.objects.filter(
        vendor=user)
    product_count = products.count()
    products = mk_paginator(request, products, 4)

    template = 'vendor/profile.html'
    context = {
        'user': user,
        "products": products,
        "product_count": product_count,
    }

    return render(request, template, context)


def vendors(request):
    vendors = Vendor.objects.all()

    template = 'vendor/list.html'
    context = {
        "vendors": vendors,
    }

    return render(request, template, context)


@login_required
def vendor_products(request):
    products = Product.objects.filter(
        vendor=request.user)

    template = 'vendor/products.html'
    context = {
        "products": products,
    }

    return render(request, template, context)


@login_required
def vendor_orders(request):
    vendor = request.user.vendor
    orders = vendor.orders.all()

    template = 'vendor/orders.html'
    context = {
        'orders': orders,
        'orders_count': orders.count()

    }

    return render(request, template, context)

templates/customer/account.html
{% extends 'base.html' %}

{% block title %}My Account{% endblock %}

{% block content %}

{% include 'partials/_alerts.html' %}

<section class="py-5 bg-light">
    <div class="container">
        <div class="row">
            {% include "partials/_customer_nav.html" %}
            <div class="col-lg-9">
                <article class="card">
                    <div class="card-body">
                        <form method="post" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'partials/_form_errors.html' %}
                            
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="row gx-3">
                                        <div class="col-6 mb-3"> 
                                            <label for="id_first_name" class="form-label">First name:</label>
                                            <input type="text" name="first_name" maxlength="150" placeholder="Enter your first name" class="form-control {% if user_form.first_name.errors %}is-invalid{% endif %}" id="id_first_name" {% if user_form.first_name.value != None %}value="{{ user_form.first_name.value|stringformat:'s' }}"{% endif %}>
                                            {% for error in user_form.first_name.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                            {% endfor %}
                                        </div>
                                        <div class="col-6 mb-3"> 
                                            <label class="form-label" for="id_last_name">Last name</label> 
                                            <input type="text" name="last_name" maxlength="150" placeholder="Enter your last name" class="form-control {% if user_form.last_name.errors %}is-invalid{% endif %}" id="id_last_name" {% if user_form.last_name.value != None %}value="{{ user_form.last_name.value|stringformat:'s' }}"{% endif %}>
                                            {% for error in user_form.last_name.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                            {% endfor %}
                                        </div>
                                        <div class="col-lg-6 col-md-6 mb-3"> 
                                            <label class="form-label" for="id_email">Email address:</label> 
                                            <input type="email" name="email" maxlength="254" placeholder="Enter your email" class="form-control {% if user_form.email.errors %}is-invalid{% endif %}" id="id_email" {% if user_form.email.value != None %}value="{{ user_form.email.value|stringformat:'s' }}"{% endif %}>
                                            {% for error in user_form.email.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                            {% endfor %}
                                        </div>
                                        <div class="col-lg-6 col-md-6 mb-3"> 
                                            <label class="form-label" for="id_phone_number">Phone number:</label> 
                                            <input class="form-control {% if customer_form.phone_number.errors %}is-invalid{% endif %}" name="phone_number" id="id_phone_number" maxlength="20" type="tel" placeholder="Enter your phone number" {% if customer_form.phone_number.value != None %}value="{{ customer_form.phone_number.value|stringformat:'s' }}"{% endif %}> 
                                        </div>
                                        <div class="col-lg-12 mb-3"> 
                                            <label class="form-label" for="id_address">Address:</label> 
                                            <input class="form-control {% if customer_form.address.errors %}is-invalid{% endif %}" name="address" maxlength="600" type="text" placeholder="Enter your primary address" id="id_address" {% if customer_form.address.value != None %}value="{{ customer_form.address.value|stringformat:'s' }}"{% endif %}> 
                                        </div>
                                    </div>
                                </div>
                                <aside class="col-lg-4">
                                    <div class="text-lg-center mt-3">
                                        <img class="img-lg mb-3 img-avatar" src="{% if user.customer.image %}{{ user.customer.image.url }}{% else %}https://via.placeholder.com/70x70{% endif %}" alt="User Photo">
                                        <div>
                                            <input type="file" name="image" accept="image/*" id="id_image" class="form-control" value="Upload">
                                        </div>
                                    </div>
                                </aside>
                            </div>
                            <button class="btn btn-primary" type="submit">Save changes</button> 
                        </form>
                        <hr class="my-4">
                        <div class="row">
                            <div class="col-md-6">
                                <article class="box mb-3 bg-light"> 
                                    <a class="btn float-end btn-outline-danger btn-sm" href="{% url 'accounts:deactivate' %}">Deactivate</a>
                                    <p class="title mb-0">Deactivate account</p> 
                                    <small class="text-muted d-block">Once you deactivate your account, there is no going back.</small> 
                                </article>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/customer/orders.html
{% extends 'base.html' %}

{% block title %}My Orders{% endblock %}

{% block content %}

{% include 'partials/_alerts.html' %}

<section class="py-5 bg-light">
    <div class="container">
        <div class="row">
            {% include "partials/_customer_nav.html" %}
            <main class="col-lg-9">
                <h5 class="mb-3"> Your orders ({{ orders_count }})</h5>
                {% for order in orders %}
                    {% include "partials/_order_card.html" %}
                {% empty %}
                    <p>You currently have no orders.</p>
                {% endfor %}
            </main>
        </div>
    </div>
</section>

{% endblock %}