carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_ecommerce/urls.py
"""django_ecommerce URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path("cart/", include("carts.urls", namespace="carts")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("products/", include("products.urls", namespace="products")),
    # password reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("", home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.index_title = "Lunch Express"
admin.site.site_header = "Lunch Express Admin"
admin.site.site_title = "Control Panel"

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('track-order/<int:id>/', views.track_order, name='track_order'),
    path('status/shipped/<int:id>/',
         views.order_status_shipped, name='order_status_shipped'),
    path('status/processing/<int:id>/',
         views.order_status_processing, name='order_status_processing'),
    path('status/completed/<int:id>/',
         views.order_status_completed, name='order_status_completed'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('c/<slug:category_slug>/', views.product_list, name='category'),
    path('vote/', views.vote_review, name="vote_review"),
    path('search/', views.product_search, name='search'),
    path('new/', views.product_create, name='create'),
    path('<int:id>/update/', views.product_update, name='update'),
    path('<int:id>/delete/', views.product_delete, name='delete'),
    path('<slug:slug>/', views.product_detail, name='detail'),
]

carts/models.py
from django.db import models

# Create your models here.

carts/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    # quantity = forms.IntegerField(
    #     min_value=1,
    #     widget=forms.NumberInput(attrs={
    #         'class': 'form-control text-center px-3',
    #         'value': 1
    #     }))
    quantity = forms.TypedChoiceField(
        label='',
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quantity'].widget.attrs.update(
            {'class': 'form-select d-inline w-25'})

carts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from products.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    View for adding products to the cart or updating quantities
    for existing products.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        messages.success(request, 'Shopping cart updated.')
    return redirect('carts:cart_detail')


@require_POST
def cart_remove(request, product_id):
    """
    View to remove a product from cart
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.info(request, 'Product removed from cart.')
    return redirect('carts:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})

    template_name = 'carts/detail.html'
    context = {
        'cart': cart
    }

    return render(request, template_name, context)

templates/carts/detail.html
{% extends 'base.html' %}

{% block title %}Your shopping cart{% endblock %}

{% block content %}

{% include 'partials/_alerts.html' %}

<section class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body p-4">
                        <h4 class="card-title mb-4">Your shopping cart</h4>
                        {% for item in cart %}
                        {% with product=item.product %}
                        <article class="row gy-3 mb-4">
                            <div class="col-lg-4">
                                <figure class="position-relative d-flex w-100 me-lg-5">
                                    <div class="position-relative flex-shrink-0">
                                        <img src="{{ product.image.url }}" class="img-sm img-thumbnail">
                                    </div>
                                    <figcaption class="flex-grow-1 ps-2">
                                        <a href="{{ product.get_absolute_url }}" class="text-decoration-none">{{ product.name }}</a>
                                    </figcaption>
                                </figure>
                            </div>
                            <div class="col-lg-3">
                                <div class="lh-sm">
                                    <var class="h6">&#8358;{{ item.total_price }}</var> <br>
                                    <small class="text-muted">&#8358;{{ item.price }} / per item </small>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <form action="{% url 'carts:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" value="Update" class="btn btn-primary">
                                </form>
                            </div>
                            <div class="col-lg-1">
                                <div class="float-lg-end">
                                    <form action="{% url 'carts:cart_remove' product.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" value="Remove" class="btn btn-light text-danger">
                                    </form>
                                </div>
                            </div>
                        </article>
                        {% endwith %}
                        {% empty %}
                        <p>You do not have any product in your cart. Continue shopping</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% if cart %}
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="d-flex">
                            <dt class="fw-normal">Total price:</dt>
                            <dd class="text-end flex-grow-1 mb-0"> &#8358;{{ cart.get_total_price }}</dd>
                        </dl>
                        <hr>
                        <dl class="d-flex">
                            <dt class="fw-normal">Total:</dt>
                            <dd class="text-end flex-grow-1 mb-0 h5"> &#8358;{{ cart.get_total_price }} </dd>
                        </dl>

                        <div class="d-grid gap-2 my-3">
                            <a href="{% url 'orders:create' %}" class="btn btn-success w-100">Checkout</a>
                            <a href="{% url 'products:list' %}" class="btn btn-outline-primary w-100">Continue shopping</a>
                        </div>
                    </div>
                </div>
            </aside>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}