accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('login/',
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True), name='login'),

    # Registration
    path('vendor/signup/', views.vendor_signup, name='vendor_signup'),
    path('customer/signup/', views.customer_signup, name='customer_signup'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # Customer account
    path('customer/', views.customer_account, name='customer'),
    path('customer/orders/', views.customer_orders, name='orders'),
    path('customer/addresses/', views.customer_addresses, name='addresses'),
    path('customer/wishlists/', views.customer_wishlist, name='wishlist'),

    # Vendor account
    path('vendors/', views.vendors, name='vendors'),
    path('vendor/', views.vendor_account, name='vendor'),
    path('vendor/orders/', views.vendor_orders, name='vendor_orders'),
    path('vendor/products/', views.vendor_products, name='vendor_products'),
    path('vendor/<str:username>/',
         views.vendor_profile, name='vendor_profile'),

    path('deactivate/', views.deactivate, name='deactivate'),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_ecommerce/urls.py
"""django_ecommerce URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path('paystack/', include(('paystack.frameworks.django.urls', 'paystack'), namespace='paystack')),
    path("cart/", include("carts.urls", namespace="carts")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("products/", include("products.urls", namespace="products")),
    # password reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("", home, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.index_title = "Lunch Express"
admin.site.site_header = "Lunch Express Admin"
admin.site.site_title = "Control Panel"

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('track-order/<int:id>/', views.track_order, name='track_order'),
    path('status/shipped/<int:id>/',
         views.order_status_shipped, name='order_status_shipped'),
    path('status/processing/<int:id>/',
         views.order_status_processing, name='order_status_processing'),
    path('status/completed/<int:id>/',
         views.order_status_completed, name='order_status_completed'),
]

orders/models.py
from datetime import datetime, timedelta
from django.db import models

from accounts.models import User, Vendor
from products.models import Product


class Order(models.Model):
    CREATED = 'Created'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    COMPLETED = 'Completed'
    # CANCELLED = 'Cancelled'
    # RETURNED = 'Returned'
    ORDER_STATUS = [
        (CREATED, 'Created'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (COMPLETED, 'Completed'),
        # (CANCELLED, 'Cancelled'),
        # (RETURNED, 'Returned'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='orders',
        blank=True, null=True) # models.SET_NULL
    # full_name?
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    # address1 / address2?
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=5)
    phone_number = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField(
        choices=ORDER_STATUS, max_length=10, default=CREATED)
    note = models.TextField(blank=True)
    delivery_date = models.DateTimeField(default=datetime.now()+timedelta(days=4))
    # transaction_id = models.CharField(max_length=200, blank=True, null=True)
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2,
        blank=True, null=True)
    paystack_id = models.CharField(max_length=150, blank=True)
    vendors = models.ManyToManyField(Vendor, related_name='orders')

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='orderitems',
        blank=True, null=True)
    vendor = models.ForeignKey(
        Vendor, related_name='items',
        on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # vendor_paid = models.BooleanField(default=False)
    # status?

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['address'].widget.attrs.update(
            {'class': 'form-control'})

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address']

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.utils.crypto import get_random_string
from django.urls import reverse
from django.conf import settings

from carts.cart import Cart
from accounts.models import LecturerPreference
from products.models import Product

from .models import OrderItem, Order
from .forms import OrderCreateForm


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user
            order.save()
            request.session['order_id'] = order.id

            total_calories = 0
            total_protein = 0
            total_carbohydrates = 0
            total_fats = 0
            total_vitamins = 0
            total_minerals = 0
            total_fiber = 0

            for item in cart:
                product = item['product']
                quantity = item['quantity']

                total_calories += product.calories * quantity
                total_protein += product.protein * quantity
                total_carbohydrates += product.carbohydrates * quantity
                total_fats += product.fats * quantity
                total_vitamins += product.vitamins * quantity
                total_minerals += product.minerals * quantity
                total_fiber += product.fiber * quantity

                if request.user.is_authenticated:
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        price=item['price'],
                        user=request.user,
                        vendor=product.vendor.vendor,
                        quantity=quantity)
                    order.vendors.add(product.vendor.vendor)
                else:
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        price=item['price'],
                        vendor=product.vendor.vendor,
                        quantity=quantity)
                    order.vendors.add(product.vendor.vendor)

            lecturer = request.user.customer
            preference, created = LecturerPreference.objects.get_or_create(lecturer=lecturer)

            # Convert preferred_calories to an integer
            preferred_calories = int(preference.preferred_calories) if preference.preferred_calories else 0
            preferred_protein = int(preference.preferred_protein) if preference.preferred_protein else 0
            preferred_carbohydrates = int(preference.preferred_carbohydrates) if preference.preferred_carbohydrates else 0
            preferred_fats = int(preference.preferred_fats) if preference.preferred_fats else 0
            preferred_vitamins = int(preference.preferred_vitamins) if preference.preferred_vitamins else 0
            preferred_minerals = int(preference.preferred_minerals) if preference.preferred_minerals else 0
            preferred_fiber = int(preference.preferred_fiber) if preference.preferred_fiber else 0

            
            # Update lecturer's nutritional preferences based on the ordered food items
            preference.preferred_calories = (preferred_calories + total_calories) // 2
            preference.preferred_protein = (preferred_protein + total_protein) // 2
            preference.preferred_carbohydrates = (preferred_carbohydrates + total_carbohydrates) // 2
            preference.preferred_fats = (preferred_fats + total_fats) // 2
            preference.preferred_vitamins = (preferred_vitamins + total_vitamins) // 2
            preference.preferred_minerals = (preferred_minerals + total_minerals) // 2
            preference.preferred_fiber = (preferred_fiber + total_fiber) // 2
            preference.save()

            # Clear the cart
            cart.clear()
            return redirect('orders:confirm_order')
    else:
        form = OrderCreateForm()
        if request.user.is_authenticated:
            initial_data = {
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'email': request.user.email,
                'address': request.user.customer.address,
                'phone_number': request.user.customer.phone_number,
            }
            form = OrderCreateForm(initial=initial_data)
    return render(request,
                  'orders/create.html',
                  {'cart': cart, 'form': form})


@login_required
def confirm_order(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)

    paystack_amount = int(order.get_total_cost())
    paystack_amount = paystack_amount * 100
    paystack_ref = None
    if not paystack_ref:
        paystack_ref = get_random_string(length=12).upper()
        order.paystack_id = paystack_ref
        order.total_amount = order.get_total_cost()
        order.save()
    paystack_redirect_url = "{}?amount={}".format(
        reverse('paystack:verify_payment',
                args=[paystack_ref]), paystack_amount, order)

    template = 'orders/confirm_order.html'
    context = {'order': order,
                   'paystack_key': settings.PAYSTACK_PUBLIC_KEY,
                   'paystack_amount': paystack_amount,
                   'paystack_redirect_url': paystack_redirect_url
    }
    return render(request, template, context)


@csrf_exempt
def payment_done(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/created.html', {'order': order})


@csrf_exempt
def payment_canceled(request):
    return render(request, 'orders/canceled.html')


@login_required
def track_order(request, id):
    order = get_object_or_404(Order, id=id)

    return render(
        request, 'orders/track_order.html', {'order': order})


@login_required
def order_status_shipped(request, id):
    order = get_object_or_404(Order, id=id)
    current_url = request.META['HTTP_REFERER']
    order.status = order.SHIPPED
    order.save()
    # send mail to user to inform him/her of change in order status
    from_email = settings.DEFAULT_FROM_EMAIL
    to_email = order.email
    send_mail(
        'Order status information',
        'Hi there, your order status has been changed to: SHIPPED',
        from_email,
        [to_email],
        fail_silently=False
    )
    messages.success(
        request, "Order status changed to: Shipped")
    return redirect(current_url)


@login_required
def order_status_processing(request, id):
    order = get_object_or_404(Order, id=id)
    current_url = request.META['HTTP_REFERER']
    order.status = order.PROCESSING
    order.save()
    # send mail to user to inform him/her of change in order status
    from_email = settings.DEFAULT_FROM_EMAIL
    to_email = order.email
    send_mail(
        'Order status information',
        'Hi there, your order status has been changed to: PROCESSING',
        from_email,
        [to_email],
        fail_silently=False
    )
    messages.success(
        request, "Order status changed to: Processing")
    return redirect(current_url)


@login_required
def order_status_completed(request, id):
    order = get_object_or_404(Order, id=id)
    current_url = request.META['HTTP_REFERER']
    order.status = order.COMPLETED
    order.save()
    # send mail to user to inform him/her of change in order status
    from_email = settings.DEFAULT_FROM_EMAIL
    to_email = order.email
    send_mail(
        'Order status information',
        'Hi there, your order has successfully been completed.',
        from_email,
        [to_email],
        fail_silently=False
    )
    messages.success(
        request, "Order status changed to: Completed")
    return redirect(current_url)

templates/orders/confirm_order.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}

{% include 'partials/_alerts.html' %}

<section class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <main class="col-lg-8 mx-auto">
                <article class="card">
                    <form method="post" action="" novalidate>
                        {% csrf_token %}
                        <div class="card-body p-4">
                            <h5 class="mb-4">Confirm Order</h5>
                            <div class="row">
                                <div class="col-6 mb-3">
                                    <label for="id_first_name" class="form-label">First name</label>
                                    <input type="text" class="form-control" value="{{ order.first_name }}" readonly>
                                </div>
                                <div class="col-6">
                                    <label for="id_last_name" class="form-label">Last name</label>
                                    <input type="text" class="form-control" value="{{ order.last_name }}" readonly>
                                </div>
                                <div class="col-6 mb-3">
                                    <label for="id_address" class="form-label">Address</label>
                                    <input type="text" class="form-control" value="{{ order.address }}" readonly>
                                </div>
                                <div class="col-6 mb-3">
                                    <label for="id_email" class="form-label">Email</label>
                                    <input type="text" class="form-control" value="{{ order.email }}" readonly>
                                </div>
                            </div>

                            <hr class="my-4">
                            <form>
                                <script src="https://js.paystack.co/v1/inline.js"></script>
                                <button class="btn btn-success" type="button" onclick="payWithPaystack()"> Pay
                                    &#8358;{{ order.get_total_cost }} With
                                    Paystack </button>
                            </form>
                        </div>
                    </form>
                </article>
            </main>

            <!-- <aside class="col-lg-4">
                <article class="ms-lg-4 mt-4 mt-lg-0">
                    <h6 class="card-title">Summary</h6>

                    <dl class="d-flex">
                        <dt class="fw-normal">Total price:</dt>
                        <dd class="text-end flex-grow-1 mb-0">&#8358;{{ order.get_total_cost }}</dd>
                    </dl>
                    <hr>
                </article>
            </aside> -->
        </div>
    </div>
</section>

<script>
    function payWithPaystack() {
        var handler = PaystackPop.setup({
            key: '{{ paystack_key }}',
            email: '{{ order.email }}',
            amount: {{ paystack_amount }},
    reference: '' + Math.floor((Math.random() * 1000000000) + 1),
        callback: function(response) {
            window.location.href = "{{ paystack_redirect_url }}&trxref=" + response.reference
        },
    onClose: function() {
        alert('Your transaction was either aborted or not completed, this window would be closed.');
    }
        });
    handler.openIframe();
    }
</script>

{% endblock %}

templates/orders/create.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}

{% include 'partials/_alerts.html' %}

<section class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <main class="col-lg-8">
                {% if not request.user.is_authenticated %}
                <article class="card mb-4">
                    <div class="card-body p-4">
                        <div class="float-end">
                            <a href="{% url 'accounts:customer_signup' %}?next={% url 'orders:create' %}" class="btn btn-outline-info">Register</a>
                            <a href="{% url 'accounts:login' %}?next={% url 'orders:create' %}" class="btn btn-outline-primary">Login</a>
                        </div>
                        <h5>Have an account?</h5>
                        <p class="mb-0">Login and make use of your saved address and track your order.</p>
                    </div>
                </article>
                {% endif %}
                <article class="card">
                    <form method="post" action="" novalidate>
                        {% csrf_token %}
                        <div class="card-body p-4">
                            <h5 class="mb-4">{% if not request.user.is_authenticated %}Guest {% endif %} Checkout</h5>
                            <div class="row">
                                <div class="col-6 mb-3">
                                    <label for="id_first_name" class="form-label">First name</label>
                                    {{ form.first_name }}
                                </div>
                                <div class="col-6">
                                    <label for="id_last_name" class="form-label">Last name</label>
                                    {{ form.last_name }}
                                </div>
                                <div class="col-6 mb-3">
                                    <label for="id_address" class="form-label">Address</label>
                                    {{ form.address }}
                                </div>
                                <div class="col-6 mb-3">
                                    <label for="id_email" class="form-label">Email</label>
                                    {{ form.email }}
                                </div>
                            </div>

                            <hr class="my-4">

                            <div class="float-end mb-4">
                                <a href="{% url 'carts:cart_detail' %}" class="btn btn-light">Cancel</a>
                                <button type="submit" class="btn btn-success">Continue</button>
                            </div>
                        </div>
                    </form>
                </article>
            </main>
            
            <aside class="col-lg-4">
                <article class="ms-lg-4 mt-4 mt-lg-0">
                    <h6 class="card-title">Summary</h6>

                    <dl class="d-flex">
                        <dt class="fw-normal">Total price:</dt>
                        <dd class="text-end flex-grow-1 mb-0">&#8358;{{ cart.get_total_price }}</dd>
                    </dl>
                    <hr>
                    <dl class="d-flex">
                        <dt class="fw-normal"> Total: </dt>
                        <dd class="text-end flex-grow-1 mb-0 h6">&#8358;{{ cart.get_total_price }}</dd>
                    </dl>

                    <hr>
                    <h6 class="mb-4">Items in cart</h6>
                    {% for item in cart %}
                    <figure class="position-relative d-flex w-100 align-items-center mb-4">
                        <div class="position-relative flex-shrink-0">
                            <b class="badge bg-secondary rounded-pill position-absolute top-0 start-100 translate-middle">{{ item.quantity }}</b>
                            <img src="{{ item.product.image.url }}" class="img-sm rounded border">
                        </div>
                        <figcaption class="flex-grow-1 ps-3">
                            <a href="{{ item.get_absolute_url }}" class="text-decoration-none">{{ item.product.name }}</a>
                            <div class="text-muted">Total: &#8358;{{ item.total_price }}</div>
                        </figcaption>
                    </figure>
                    {% endfor %}
                </article>
            </aside>
        </div>
    </div>
</section>

{% endblock %}

templates/orders/created.html
{% extends 'base.html' %}

{% block title %}Order successful{% endblock %}

{% block content %}

<section class="py-3 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <article class="card my-4">
                    <div class="card-body mb-4">
                        <div class="mt-4 mx-auto text-center"> 
                            <svg width="96px" height="96px" viewBox="0 0 96 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"> <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="round-check"> <circle id="Oval" fill="#D3FFD9" cx="48" cy="48" r="48"></circle> <circle id="Oval-Copy" fill="#87FF96" cx="48" cy="48" r="36"></circle> <polyline id="Line" stroke="#04B800" stroke-width="4" stroke-linecap="round" points="34.188562 49.6867496 44 59.3734993 63.1968462 40.3594229"></polyline> </g> </g> </svg>
                            <div class="my-3">
                                <h4>Thank you for your order</h4>
                                <p>Your order has been successfully received. Your order number is <strong>{{ order.id }}</strong>, <br>and it will be available to you in the next <strong>5 minutes</strong>.</p>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/orders/email_notify_customer.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <h1>Order successful</h1>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Details</h3>
                <b>Name:</b> {{ order.first_name }} {{ order.last_name }}
            </td>
        </tr>
        <tr>
            <td>
                <h3>Products</h3>
                <table>
                    <tr>
                        <td>Product</td>
                        <td>Price</td>
                    </tr>

                    {% for item in order.items.all %}
                    <tr>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.product.price }}</td>
                    </tr>
                    {% endfor %}

                </table>
            </td>
        </tr>
    </table>
</body>

</html>

templates/orders/email_notify_vendor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td><h1>New Order</h1></td>
        </tr>
        <tr>
            <td>
                <h3>Details</h3>
                <b>Name:</b> {{ order.first_name }} {{ order.last_name }}
            </td>
        </tr>
        <tr>
            <td>
                <h3>Products</h3>
                <table>
                    <tr>
                        <td>Product</td>
                        <td>Price</td>
                    </tr>
                    
                    {% for item in order.items.all %}
                    {% if item.vendor == vendor %}
                    <tr>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.product.price }}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    
                </table>
            </td>
        </tr>
    </table>
</body>
</html>

templates/orders/track_order.html
{% extends 'base.html' %}

{% block title %}Track Order: {{ order.id }}{% endblock %}

{% block content %}

<section class="py-3 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <article class="card my-4">
                    <div class="card-body mb-4">
                        <a class="btn btn-light" href="{% url 'accounts:orders' %}">&laquo; Go back</a>
                        <div class="mt-4 mx-auto text-center"> 
                            <div class="my-3">
                                <h4>Track your order</h4>
                                <p>Below is the status of your order #<strong>{{ order.id }}</strong>.</p>
                            </div>
                        </div>
                        <ul class="steps-wrap mx-auto">
                            <li class="step {% if order.status == 'Created' or order.status == 'Processing' or order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                                <span class="icon">1</span> 
                                <span class="text">Order received</span> 
                            </li>
                            <li class="step {% if order.status == 'Processing' or order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                                <span class="icon">2</span> 
                                <span class="text">Order processing</span> 
                            </li>
                            <li class="step {% if order.status == 'Shipped' or order.status == 'Completed' %}active{% endif %}"> 
                                <span class="icon">3</span> 
                                <span class="text">Order shipped</span> 
                            </li>
                            <li class="step {% if order.status == 'Completed' %}active{% endif %}"> 
                                <span class="icon">4</span> 
                                <span class="text">Order delivered</span>
                            </li>
                        </ul>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endblock %}